files:
  - source: translation/en/dictionary.json
    translation: /translation/%two_letters_code%/dictionary.json
    update_option: update_as_unapproved
  - source: translation/en/en.json
    translation: /translation/%two_letters_code%/%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/re-en.json
    translation: /translation/%two_letters_code%/re-%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/action-en.json
    translation: /translation/%two_letters_code%/action-%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/kingmaker-en.json
    translation: /translation/%two_letters_code%/kingmaker-%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/*.json
    ignore:
      - equipment.json
      - feats.json
      - spells.json
      - actions.json
      - macros.json
      - conditions.json
      - mwangi-expanse-bestiary.json
      - travel-guide-bestiary.json
      - monsters-of-myth-bestiary.json
      - highhelm-bestiary.json
      - impossible-lands-bestiary.json
      - fall-of-plaguestone.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/feats.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/equipment.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/spells.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/actions.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%pf2e.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/macros.json
    translation: /translation/%two_letters_code%/compendium/pf2e.pf2e-%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/conditions.json
    translation: /translation/%two_letters_code%/compendium/pf2e.conditionitems.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/mwangi-expanse-bestiary.json
    translation: /translation/%two_letters_code%/compendium/pf2e.lost-omens-mwangi-expanse-bestiary.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/travel-guide-bestiary.json
    translation: /translation/%two_letters_code%/compendium/pf2e.lost-omens-travel-guide-bestiary.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/monsters-of-myth-bestiary.json
    translation: /translation/%two_letters_code%/compendium/pf2e.lost-omens-monsters-of-myth-bestiary.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/highhelm-bestiary.json
    translation: /translation/%two_letters_code%/compendium/pf2e.lost-omens-highhelm-bestiary.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/impossible-lands-bestiary.json
    translation: /translation/%two_letters_code%/compendium/pf2e.lost-omens-impossible-lands-bestiary.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/fall-of-plaguestone.json
    translation: /translation/%two_letters_code%/compendium/pf2e.fall-of-plaguestone-bestiary.json
    update_option: update_as_unapproved