files:
  - source: translation/en/dictionary.json
    translation: /translation/%two_letters_code%/dictionary.json
    update_option: update_as_unapproved
  - source: translation/en/en.json
    translation: /translation/%two_letters_code%/%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/re-en.json
    translation: /translation/%two_letters_code%/re-%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/action-en.json
    translation: /translation/%two_letters_code%/action-%two_letters_code%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/*.json
    ignore:
      - equipment.json
      - feats.json
      - spells.json
      - actions.json
      - macros.json
      - conditions.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/feats.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/equipment.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/spells.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/actions.json
    translation: /translation/%two_letters_code%/compendium/pf2e.%file_name%pf2e.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/macros.json
    translation: /translation/%two_letters_code%/compendium/pf2e.pf2e-%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/conditions.json
    translation: /translation/%two_letters_code%/compendium/pf2e.conditionitems.json
    update_option: update_as_unapproved
