name: Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Sync packs and Commit Changes
        run: |
          npm ci
          git config user.email "action@github.com"
          git config user.name "Github Action"
          npm run db-extractor
          git add translation/en
          git commit -m "Sync packs"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Sync packs'
          commit-message: 'Sync PF2 pack updates into main'
          branch: sync-packs
          body: |
            Sync PF2 pack updates into main
            
      #- name: Merge Pull Request
      #  run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
