name: Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Sync packs and Commit Changes
        run: |
          npm ci
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git checkout -b sync-packs
          npm run db-extractor
          git add translation/en
          git commit -m "Sync packs"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Sync packs'
          commit-message: 'Sync PF2 pack updates into main'
          branch: main
          base: sync-packs
          body: |
            Sync PF2 pack updates into main
            
     # - name: Merge Pull Request
     #   uses: peter-evans/merge-pull-request@v3
      #  with:
      #    pull-number: ${{ steps.create_pr.outputs.pull-request-number }}
      #    merge-method: 'merge'
      #    commit-message: 'Merge pull request'
      #    delete-branch: true
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Commit updated packs
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    add: 'translation/en'
